version: "3.8"

services:
  postgres:                   # 서비스 이름을 'postgres'로 변경
    build:
      context: .
      dockerfile: dockerfile_postgres
    container_name: postgres  # 컨테이너 이름을 'postgres'로 지정
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1250"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
